.travis.yml, README.md, server/stats.go
For the 3rd time the influx API has changed making SkyDNS failing
to compile.
Just removed influx support all together.
=> Remove influx

main.go
In newClient the 'tlspem' and 'tlskey' parameters were reversed.
Todo: tests ssl conn. to Etcd.
Closes issue #130
=> Use cert and key in correct order for TLS conn. to Etcd.

.travis.yml, README.md, msg/service.go, server/forwarding.go, server/server.go, server/server_test.go
From the README.md: 
If you ask for a service who's Host value is an IP address you would (in theory) get 
back a SRV record such as: 
% dig @localhost 4.rails.staging.east.skydns.local SRV
;; ANSWER SECTION:
4.rails.staging.east.skydns.local 3600 IN SRV 10 100 8080 10.0.1.125
Where the target of the SRV is an IP address. This is not how SRV records work.
SkyDNS will in this case synthesize a domain name and add the actual IP
address to the additional section of the response:
% dig @localhost 4.rails.staging.east.skydns.local SRV
;; ANSWER SECTION:
4.rails.staging.east.skydns.local 3600 IN SRV 10 100 4.rails.staging.east.skydns.local.
;; ADDITIONAL SECTION:
4.rails.staging.east.skydns.local. 3600 IN A    10.0.1.125
Which conveys the same information and is legal in the DNS. To have some …
=> Add TargetStrip to msg.Service

README.md, main.go
Tiny fix: fix some typo ectd to etcd.
=> fix typo: ectd -> etcd

Dockerfile
Using a busybox only is annoying because there isn't a good dig
equiv. Having access to packages, in this case openwrt, makes sense
because it makes live much easier.
Total size is 15.13 MB.
=> Base image of progrium/busybox

README.md, msg/service.go, server/server.go, server/server_test.go
Add support for MX records, by extending `msg.Service`, with a `Mail` boolean field. Add 2-line explanation to the README.
=> Add MX record support.

Dockerfile, README.md
progium/busybox will soon be deprecated and they point to Alpine
Linux. Make the changes to our repo and document how to build
SkyDNS because Alpine Linux used musl libc instead of glibc.
=> Base docker image out of Alpine Linux

README.md
See issue #195, the nameservers must be *under* ns.dns. not at ns.dns.
Make the documentation more clear that this should be the case.
=> Make it clearer how to set nameservers

server/config.go
It should be possible to run SkyDNS with no nameservers on a host that
has no /etc/resolv.conf
Hit this when running skydns in Docker and empty DNS settings were passed.
=> If host has no /etc/resolv.conf, don't error out

README.md, main.go
This comes in handy when it's easy to modify environment variables, but it's difficult to modify the actual command line used to start skydns.
I'm running into this situation with Fedora's skydns package, but it seems like systemd encourages this style, so I assume this change would make other people's lives easier as well.
Thank you very much for skydns! It's making my life so much easier!
=> Env config support for systemd socket activation

README.md
Several command line flags are not described in the README. Command line flags may overwrite environment variables, this change clarifies which flags overwrite environment variables.
=> Add missing command line flags to README

Dockerfile
This PR changes the Dockerfile to use the latest available alpine image, not the older 3.1 image.
=> Dockerfile: use latest alpine image

.travis.yml
Hi,
i updated the .travis.yaml that th etests will run now on Go 1.5 and Go 1.6
Best wishes,
Matthias
=> Run tests with Go 1.5 and 1.6 on TravisCI

main.go
Fixes #276.
It's better to panic and pass the control to the process manager (systemd, docker, ...) than to continue with an unexpected configuration.
(.travis stuff are dropped, as discussed in #277)
=> Falling back to the default config doesn't make sense

README.md, main.go
Fix #228. I think skydns has already support etcd auth, what we want is support etcd basic auth(username&password), am I right? If so I will open a new PR to implement this, this PR rewrite etcd client construction logical.
=> add support for etcd basic auth

server/server.go
First off, thank's for including prometheus metrics in your service and making it easy to expose for scraping because of that it was easy to get some stats!
However as I try to build some dashboards and alerting on the metrics I'm having a hard time with the results.
As an example I would expect `dns_request_count` to be a total count of every DNS request the server has received, regardless of how the request was handled. Instead it seems the metric is only incremented in a few different cases but the primary case of serving a DNS request such as `A` for a domain its auth for is not one of them.
This should get those requests included in the counter.
=> increment request count for auth system

server/stub.go
When a forwarded UDP stubzone request is unable to complete due to response truncation, the truncate message should be returned to the client so that the client may switch to TCP. How this should interact with retrying across multiple nameservers is less clear (what if a different nameserver would have returned a non-truncated response?)
=> Immediately forward truncate errors when proxying requests.

README.md, backends/etcd/etcd.go, backends/etcd3/etcd3.go, main.go, server/config.go
Aims to provide an parameter way of support for skydns.
Default skydns supports etcd v2.
TTL computation for etcd version 3 will be only by default, until RPC for its support is ready in etcdv3.
=> Etcd version 3 support for skydns

backends/etcd/etcd.go, backends/etcd3/etcd3.go, server/backend.go, server/server.go
Adds HasSynced to Backend interface. This allows skydns to ensure that its backend has done whatever syncing it needs to do responding to queries (i.e syncing services & endpoints from k8s api server). This change is necessary to fix https://github.com/kubernetes/dns/issues/186. If the backend is not synced, then skydns will return REFUSED.
Despite being introduced because of a kube-dns issue, HasSynced() is still meant to be generic and can be used by any backend. If a backend does not care about syncing, it can simply return true in the implementation.
A corresponding change will be made in kube-dns to implement HasSynced().
=> Add HasSynced() to Backend interface

Gopkg.lock, Gopkg.toml, metrics/metrics.go
The current constraint is to use 0.8.0. 
This causes some dependency issue in our repo - https://github.com/kubernetes/dns/blob/master/Gopkg.toml
We want to use newer coreDNS versions that use a newer prometheus golang client. The change in this PR will help with that.
=> Use prometheus client 1.1.0

server/stub.go
This was removed from miekg/dns in commit - https://github.com/miekg/dns/commit/1ff265a78454967a4321dc2c0e38e267323bc3d4#diff-8353741544373e78bb7c8c3f6a0ea2cc.
The commit message recommendatation is to check for the unpack error
which the current code is doing. Conn.ReadMsg returns err is unpack
fails.
=> Remove checking for ErrTruncated, which is now removed.
